AnimalsStickers:
  - AnimalType: "кот"
    StickerId: "AgADSUYAApmduUo"
  - AnimalType: "заяц"
    StickerId: "AgADEEAAAklzwUo"
  - AnimalType: "дракон"
    StickerId: "AgADij8AAjnzwUo"
  - AnimalType: "единорог"
    StickerId: "AgAD80EAAi9KuEo"
StickerExample: "CAACAgIAAxkBAAOaZdx54b2HXZEYcU-XKwc8ipEDfMMAAklGAAKZnblK28GYvB9jViI0BA"